version: '3.8'

services:
  postgres:
    container_name: laricroche_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: laricroche
